### ISSUE TITLE
The project is still alive?

### ISSUE THREAD

**Issue by stkrp** [uniphil/parrot#1]
https://pypi.python.org/pypi/parrot/0.0.0
Hey. You still need a name for package?
I'm doing a small library for parsing sites-catalogs: https://bitbucket.org/stkrp/parrot/.

**Comment by uniphil** [comment]
hi! sorry, I've been afk for the holidays. still want parrot? It's yours if you do!

**Comment by stkrp** [comment]
I changed the status of the repository on the "public", and you can review it. 
But I have not written the documentation for the library, because I thought that it didn't come out in public access.

> It's yours if you do!

Thank you very much!  What do I need to do?

**Comment by uniphil** [comment]
> What do I need to do?

Hopefully nothing! I'm assuming your pypi username is `stkrp` -- I added you as an "owner" on pypi, and deleted the 0.0.0 empty parrot release I had up there.

If that's not your pypi username, let me know and I'll fix it, unless the person who's not you and has the `stkrp` username is evil and removes me from pypi first :smile: 

If it is you, feel free to remove me as an owner (I think you can?), or confirm here and I'll try to remove myself.

Sorry for all the delays, and good luck with your project!

**Comment by stkrp** [comment]
I did everything you said and downloaded the first version, but it is still quite raw. Thank you!

**Comment by uniphil** [comment]
Woo! :cake:
